name: Snap

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Build Snap
      id: build
      run: |
        snapcraft
        SNAP_NAME=$(ls *.snap)
        echo "SNAP_NAME=${SNAP_NAME}" >> $GITHUB_ENV
    - name: Publish Snap
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ env.SNAP_NAME }}
        release: edge

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Build Snap
      id: build
      run: |
        snapcraft
        SNAP_NAME=$(ls *.snap)
        echo "SNAP_NAME=${SNAP_NAME}" >> $GITHUB_ENV
    - name: Publish Snap
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ env.SNAP_NAME }}
        release: edge